version: '3'

services:
  brain-hike:
    build:
      context: .
      dockerfile: Dockerfile
    image: unfaiyted/brain-hike
    container_name: brain-hike
    restart: unless-stopped
    depends_on:
      - brain-hike-swag
  brain-hike-swag:
    image: linuxserver/swag
    container_name:  brain-hike-swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config/:/config
      - ./build/:/build
    environment:
      - EMAIL=miller.l.dane@gmail.com
      - URL=faiyt.dev
      - SUBDOMAINS=www,api
      - VALIDATION=http
      - TZ=Europe/London
      - PUID=0
      - PGID=0
